### ISSUE TITLE
failed to compile helloworld

### ISSUE THREAD

**Issue by dvdrbls** [napframework/nap#1]
hello, I really like to test this framework, i didn't had visual studio 2015 so I installed it along with 2017 that I use for openframeworks, I got this error in 2015 update 3 trying to compile helloworld 
![Capture](https://user-images.githubusercontent.com/5351941/101495784-9110ac80-392e-11eb-9059-1e70bba64846.JPG)

what can I do, as you can see both cl.exe skipped

thanks
David

**Comment by cklosters** [comment]
Hi David,

From your output it looks the helloworld solution (and therefore project) generated just fine. I assume you are working from a pre-compiled package and not NAP Source code? You should be able to open the solution the build system created for you in: `demos\helloworld\msvc64\helloworld.sln` and compile it:"

![image](https://user-images.githubusercontent.com/2768147/101606168-5a589600-3a03-11eb-9601-9c2ac012c8db.png)

Unlike Openframeworks NAP uses a build system to create a solution for your project, including all modules and third party dependencies. You then open this solution to compile the project and run it. I highly recommend you read the NAP distributable package installation instructions, including how to compile and run a demo, here: https://www.napframework.com/doxygen/d9/d87/install.html

If you work against NAP source code you generate a solution for the entire NAP code base, including all demos, tools etc.

**Comment by cklosters** [comment]
I haven't heard anything back and since this is not a bug I'm closing the issue. If you run into a specific issue with the source code feel free to create another ticket.
