### ISSUE TITLE
GUI scaling bugs when using secondary display

### ISSUE THREAD

**Issue by CasimirGeelhoed** [napframework/nap#13]
Hi NAP team!

We found a few issues related to the DPI-dependent GUI scaling in NAP 0.5. The bugs below were encountered when using a high resolution primary display (Retina or 4K) and a lower resolution secondary display (Full HD). This is a situation that is relatively common for our users (who might use an external display with their MacBook). The bugs have also been reproduced on Windows unless noted otherwise.

Bug 1: When dragging the app window to a newly connected monitor, the GUI become unusually large.

1. start up the Hello World demo without the secondary display connected
2. connect the secondary display
3. drag the app window to the secondary display

![Screenshot 2022-09-16 at 12 38 20 (2)](https://user-images.githubusercontent.com/8721625/190626380-7f6b26ec-3214-4361-bbc0-00136fe693fc.png)

Bug 2 (only on MacOS): The size of ImGUI windows is much larger in relation to the app window on the secondary/lower resolution display. This is especially a problem when the ImGUI window gets larger than the app window itself: in this case it becomes impossible to manually resize the ImGUI window.

After starting up the Hello World demo:
<img width="1792" alt="Screenshot 2022-09-16 at 12 32 01" src="https://user-images.githubusercontent.com/8721625/190627140-fc01036c-54e3-4277-bbb1-ad9d22c01a8b.png">

After dragging the app window to the secondary display:
![Screenshot 2022-09-16 at 12 32 09 (2)](https://user-images.githubusercontent.com/8721625/190627103-ef08c6fa-e0a4-4aee-abf5-7abfce349fab.png)

Bug 3: When placing the app window around the halfway point between the secondary display and the first display, the GUI becomes unusually large:

![Screenshot 2022-09-16 at 12 32 18 (2)](https://user-images.githubusercontent.com/8721625/190628174-c6c642a4-152c-4491-aaa2-c248cfe65838.png)

**Comment by cklosters** [comment]
It's been 3 weeks without a reply, closing issue.
