### ISSUE TITLE
Duplicating MaterialInstance with uniforms invalidates data

### ISSUE THREAD

**Issue by lshoek** [napframework/nap#36]
Steps to reproduce:

- Open `helloworld` in Napkin
- Add an uniform struct to the material instance of `nap::RenderableMeshComponent` in the `World` entity
- This should automatically create constant shader uniform members
- Duplicate said `nap::RenderableMeshComponent`
- Run `helloworld`
- The data is invalid

Napkin should probably generate new IDs for the duplicated uniforms as well. I have also had this happen with `BufferBinding`

**Comment by cklosters** [comment]
I can reproduce this issue. It occurs because the nap::MaterialInstance is not a resource or resource pointer, therefore it is not deep copied. From what I know this is the only object in the NAP system that has these properties. I need to think of a proper solution for this one.

**Comment by cklosters** [comment]
Fixed here: https://github.com/napframework/nap/pull/37
