### ISSUE TITLE
Unused condition warning

### ISSUE THREAD

**Issue by stijnvanbeek** [napframework/nap#56]
https://github.com/napframework/nap/blob/167861342436b65afb209ef31f5f7394adc44e3e/system_modules/naprender/src/samplerinstance.h#L220

Hi,

this line generates warnings on my platform and it looks like the condition is either unnecessary or should been an assert..

**Comment by lshoek** [comment]
Can confirm this should have been an assert

**Comment by cklosters** [comment]
Yes, that should have been an assert.

**Comment by cklosters** [comment]
Fixed here: https://github.com/napframework/nap/commit/a823e23602bca9f15f0cc7ba8d14595155387832
