### ISSUE TITLE
Non copyable incoming OSC messages

### ISSUE THREAD

**Issue by stijnvanbeek** [napframework/nap#62]
I need to dispatch OSCEvent messages handled by OSCInputComponent to a different thread in order to handle them there. I run into the problem that the const OSCEvent& is non copyable and therefore cannot be saved anywhere beyond its lifespan on the main thread.

Two possible solutions could be:
1. Implement a copy or move constructor for OSCEvent.
2. Instead of const OSCEvent& forward the std::unique_ptr<const OSCEvent> to the OSCInputComponent. This way the pointer can be moved into a cueue that can be processed on a different thread.

Any thoughts or preference about this?

Update: moving might not be an option here as the OSCEvent is possibly handled by different OSCInputComponents at the same time.

**Comment by cklosters** [comment]
Events are not really meant to be copied, they are constructed and owned by the object they're moved into (if they're a pointer). If you want to copy an event you can create a deep copy using RTTI by making the arguments a property. Haven't looked into it myself but I don't see why this is an issue I should resolve because it's not something we want to support?

If it's specific to something you're running into it's probably best if you resolve it for your case.

**Comment by stijnvanbeek** [comment]
If you read my message you can see I didn't ask you or Tim need to resolve anything.
Was just curious to hear thoughts before changing anything in OSCEvent and making a pull request that would not be accepted anyway.
Unfortunately I am in a usecase where I cannot handle events on the main thread.
Thanks for the tip about nap::rtti::copyObject.

**Comment by cklosters** [comment]
> If you read my message you can see I didn't ask you or Tim need to resolve anything.

If that's the case don't explicitly assign the issue to me or Tim the next time - this makes us feel responsible for resolving it.

>... it breaks backwards compatibility for example.

Backwards compatibility should never be broken unless there is no other option. You are right that therefore the PR would not be accepted.

 > Unfortunately I am in a usecase where I cannot handle events on the main thread.

In that case you should make a copy and store it local to your thread, this ensures that the object that owns the event can destroy it after it being dispatched.
