### ISSUE TITLE
NAP arm64 download link broken.

### ISSUE THREAD

**Issue by dotcomadot** [napframework/nap#76]
Hello Folks, 
Just wanted to report that the [NAP-0.7.5-Linux-arm64.tar.bz2] download link is broken.

**Comment by cklosters** [comment]
Hi @dotcomadot, thanks for pointing that out. I fixed it here: https://github.com/napframework/nap/releases/tag/v0.7.5

Maybe good to know that you can always download the latest version of NAP Framework at: https://download.nap-labs.tech - the build server automatically publishes the build there after a successful run & check of the main branch. Right now the latest version available is [v0.7.7](https://download.nap-labs.tech/dist/NAP-0.7.7-Linux-arm64.tar.bz2)
